### ISSUE TITLE
Permission issues with pushing to repo

### ISSUE THREAD

**Issue by JasonCiemielewski** [BIFX552-24/markdown-quarto-JasonCiemielewski#1]
received error

$ git push -u origin main

remote: Permission to BIFX552-24/markdown-quarto-JasonCiemielewski.git denied to JasonCiemielewski.
fatal: unable to access 'https://github.com/BIFX552-24/markdown-quarto-JasonCiemielewski.git/': The requested URL returned error: 403

**the .git/config** 
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/BIFX552-24/markdown-quarto-JasonCiemielewski.git
        fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by johnsonra** [comment]
This looks like a permissions error. Are you using a command line token? You'll need to [set one up on GitHub](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic) before pushing from the command line (or cloning/pulling from a private repository). Set up a classic token and select the Repo access boxes in the first section under "select scopes". One of the videos from this week will walk you through that.

**Comment by JasonCiemielewski** [comment]
I am not sure how to provide git the token.  Git does not prompt me for the token.  I generated the 7-day token when performing the toyPipeline exercise, and I still have that token ID saved in a separate txt file.

**Comment by JasonCiemielewski** [comment]
I am not 100% sure how I fixed the issue.

I verified that I was using HTTPS and not SSH.  I fiddled with some Sourcetree settings, which caused the prompt for the token next time I attempted to push.  I think something in my Sourcetree settings was causing the issue.
